---
before_install:
  - "echo \"$DOCKER_PASSWORD\" | docker login -u \"$DOCKER_USERNAME\" --password-stdin"
  - "cat VERSION | xargs -I{} docker build -t tibbar/golang-microservice-example:{} ."
  - "cat VERSION | xargs -I{} docker push tibbar/golang-microservice-example:{}"
  - "docker build -t tibbar/golang-microservice-example:latest ."
  - "docker push tibbar/golang-microservice-example:latest"
language: bash
services:
  - docker